name: Deploy MkDocs Docs

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install MkDocs and plugins
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install \
            mkdocs \
            mkdocs-material \
            mkdocs-click \
            mkdocstrings \
            mkdocstrings-python \
            mkdocs-include-markdown-plugin \
            --upgrade

      - name: Symlink README into docs
        run: |
          cp --remove-destination README.md docs/index.md

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email yolov5.deepsort.pytorch@gmail.com
          git config --local user.name mikel-brostrom
          mkdocs gh-deploy --clean --force --verbose
